---
abstract: 'Show process I/O operations'
author:
  - 'Josh Jore <jjore@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ProcIops
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-ProcIops
  homepage: http://search.cpan.org/dist/App-ProcIops
  repository: git://github.com/jbenjore/App-ProcIops.git
version: 0.002
